# Generated by Django 6.1.2 on 2026-10-08 14:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, null=True)),
                ('color', models.CharField(max_length=100, null=True)),
                ('memory', models.CharField(max_length=50, null=True)),
                ('manufacturer', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField(null=True)),
                ('sale_price', models.IntegerField(null=True)),
                ('product_code', models.CharField(max_length=50, null=True)),
                ('reviews_count', models.IntegerField(null=True)),
                ('screen_diagonal', models.CharField(max_length=50, null=True)),
                ('display_resolution', models.CharField(max_length=50, null=True)),
                ('photos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500, null=True), null=True)),
                ('characteristics', models.JSONField(null=True)),
                ('link', models.URLField(max_length=500, null=True)),
                ('source', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
